# TODO:
# - Separate logs for postgres and backend

name: nsjwf

services:
  postgresql:
    image: postgres:16
    container_name: "pg16"
    ports:
      # HostPort:ContainerPort
      # ContainerPort is used between containers, HostPort is used between host and container.
      - "9000:5432"
    environment:
      POSTGRES_USER: "mike"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "mydb"
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    init: true
    container_name: "node_backend"
    build:
      context: .
      target: dev # if use "prod", don't use --watch flag when using docker compose up
      # Fix docker fails to reach debian.org
      network: host # https://stackoverflow.com/a/66714888
    ports:
      # HostPort:ContainerPort
      - "8000:8000"
    volumes:
      - uploads:/usr/local/app/uploads
    develop:
      watch:
        # sync alone doesn't seem to work, probably ts-node-dev issue
        - action: sync
          path: ./src
          target: /usr/local/app/backend/src
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
        - action: sync+restart
          path: .env
          target: /usr/local/app/backend/.env

volumes:
  db-data:
    external: true
    name: "nsjwf-pg"
  uploads:
    external: true
    name: "nsjwf-uploads"
