export enum ProductStockChangeReason {
  VENDOR_ORDER = "VENDOR_ORDER",
  CUSTOMER_ORDER = "CUSTOMER_ORDER",
  VENDOR_RETURN = "VENDOR_RETURN",
  CUSTOMER_RETURN = "CUSTOMER_RETURN",
  DAMAGED = "DAMAGED",
  EMPLOYEE_BORROW = "EMPLOYEE_BORROW",
  SELF = "SELF",
  UNKNOWN = "UNKNOWN",
}