export enum ProductStockChangeReason {
  VENDOR_ORDER_COMPLETED = "VENDOR_ORDER_COMPLETED",
  CUSTOMER_ORDER_CREATE = "CUSTOMER_ORDER_CREATE",
  CUSTOMER_ORDER_EDIT = "CUSTOMER_ORDER_EDIT",
  VENDOR_RETURN_RECEIVED = "VENDOR_RETURN_RECEIVED",
  CUSTOMER_RETURN_RECEIVED = "CUSTOMER_RETURN_RECEIVED",
  DAMAGED = "DAMAGED",
  EMPLOYEE_BORROW = "EMPLOYEE_BORROW",
  SELF_CREATE = "SELF_CREATE",
  SELF_EDIT = "SELF_EDIT",
  UNKNOWN = "UNKNOWN",
}
