export enum StockChangeReason {
  VENDOR_ORDER_COMPLETED = "VENDOR_ORDER_COMPLETED",
  CUSTOMER_ORDER_COMPLETED = "CUSTOMER_ORDER_COMPLETED",
  VENDOR_RETURN_RECEIVED = "VENDOR_RETURN_RECEIVED",
  CUSTOMER_RETURN_RECEIVED = "CUSTOMER_RETURN_RECEIVED",
  DAMAGED = "DAMAGED",
  EMPLOYEE_BORROW = "EMPLOYEE_BORROW",
  SELF_ADD = "SELF_ADD",
  SELF_USE = "SELF_USE",
  UNKNOWN = "UNKNOWN",
}
