name: prod_deployment
run-name: ${{ github.actor }} triggered ${{ github.action }} workflow.
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # Used by Ansible
      SERVER_IP: ${{ secrets.HOST }}
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install pipx
        run: |
          python3 -m pip install --user pipx
          python3 -m pipx ensurepath

      - name: Install Ansible and dependencies
        run: |
          pipx install ansible-core
          ansible-galaxy collection install community.docker

      - name: Configure SSH
        run: |
          mkdir ~/.ssh && chmod 0700
          echo "${{ secrets.PKEY }}" > ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519
          echo "${{ secrets.HOST }} ssh-ed25519 ${{ secrets.HOST_PUBLIC_KEY }}" > ~/.ssh/known_hosts

      - name: Check Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory.yml --syntax-check ansible/deploy-playbook.yml

      - name: Test Ansible connection
        run: |
          ansible backend -m ping -i ansible/inventory.yml

      - name: Run Ansible playbook
        run: |
          ansible-playbook -i ansible/inventory.yml ansible/deploy-playbook.yml -e "force=true"
