name: dev-deployment
run-name: ${{ github.actor }} triggered this workflow.
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - run: echo "Something something"
      - uses: appleboy/ssh-action
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PKEY }}
          script: |
            whoami
            pwd
            cd storage/backend
            git pull origin dev
