name: dev-deployment
run-name: ${{ github.actor }} triggered this workflow.
on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # - run: echo "Something something"
      - uses: appleboy/ssh-action@029f5b4aeeeb58fdfe1410a5d17f967dacf36262
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.PKEY }}
          script: |
            cd ~/.ssh
            ls
            cd ~/storage/backend
            git pull origin dev
